server:
  port: 8080
  redis:
    host: localhost
    port: 6379
    password: # 如果设置了密码，则填写密码
    database: 0 # Redis数据库索引（默认为0）
spring:
  application:
    name: schedule-util
  profiles:
    active: dev